### ISSUE TITLE
Back button for darts causes player to enter darts rather than back out

### ISSUE THREAD

**Issue by josephcyang4459** [josephcyang4459/Duo-Darts#100] opened 2024-04-10 17:54 UTC
https://github.com/josephcyang4459/Duo-Darts/assets/65678477/e30bae90-2aa0-40a6-8406-ca9137e8aa8f

**Comment by josephcyang4459** [comment] 2024-04-10 19:01
Looks like this was partially finished, it just needs to be finished by completing the buttons and setting the order of it so that it can be clicked on top of the other canvas objects (good luck soldier). Below is where you can find the buttons.
![image](https://github.com/josephcyang4459/Duo-Darts/assets/65678477/a218dfb5-ce92-4f35-878c-13d5eee4ab74)

**Comment by LipglossBPoppin** [comment] 2024-04-10 20:48
No it is not partially finished this is once again because you are running the game below native resolution i will deploy a fix for this because it is some simple multiplication, but those buttons are exactly where they are supposed to be.

**Comment by josephcyang4459** [comment] 2024-04-10 21:29
> No it is not partially finished this is once again because you are running the game below native resolution i will deploy a fix for this because it is some simple multiplication, but those buttons are exactly where they are supposed to be.

Yep, found this out from your explanation on one of the other issues! Sorry about that.

**Comment by LipglossBPoppin** [comment] 2024-07-20 07:51
External play testing has found that this is still an issue unfortunately. I have a possible fix in mind, if the issue is what I think it is. I think it's still buffering the input on the click, so darts partner menu click should I lay register click on canceled rather than on performed.

**Comment by LipglossBPoppin** [comment] 2024-07-20 07:55
Looks like my previous post was already implemented as a fix... Welp. I'll continue to work on this.

**Closed** 2024-11-21 07:41 UTC
Labels: Non-Darts Gameplay, Misc
